### ISSUE TITLE
GPIO floating whilst power over ethernet and using internal pullup

### ISSUE THREAD

**Issue by trevm8** [OLIMEX/ESP32-POE#18]
I am using a pushbutton connected to GPIO3 and configured to use the internal pull-up resistor. I find that when I have non-powered wired ethernet connected and USB powered - the code executes as expected with consistent results recorded.

However; when I use the POE functionality, whilst using the exact same code - GPIO3 is now read as constantly changing low to high (floating).

I am using a TP-Link POE switch

**Comment by DanKoloff** [comment]
It should work but my general advice is to avoid using GPIO3 since it is connected to CH340T. 
![gpio3-ch340t](https://user-images.githubusercontent.com/6028552/100074169-184a2480-2e47-11eb-8eb4-ea67f1940187.jpg)

However, if there is no way to avoid using it, try with external pull-up maybe the internal one is not good enough. I suspect when CH340T is not powered, maybe it gets powered from the GPIO3 line for some reason.
